module Xuanming
  VERSION_MAJOR = 0
  VERSION_MINOR = 0
  VERSION_BUILD = 1
  VERSION_PRE   = 'pre1'
  VERSION       = [VERSION_MAJOR, VERSION_MINOR, VERSION_BUILD, VERSION_PRE].compact.join(".")
end
